name: CI - Build and push tagged docker image to dockerhub

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag name in env
        env:
          IMAGE_NAME: covergan-frontend
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          RELEASE_VERSION=${RELEASE_VERSION:1}
          echo "DOCKER_TAG_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$RELEASE_VERSION" >> "$GITHUB_ENV"
          echo "DOCKER_LATEST_TAG_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest" >> "$GITHUB_ENV"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_LATEST_TAG_NAME }},${{ env.DOCKER_TAG_NAME }}
