name: CI (build docker image)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag name in env
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${RELEASE_VERSION:1}" >> "$GITHUB_ENV"
          echo "TAG_NAME=izhanvarsky/covergan-frontend:$RELEASE_VERSION" >> "$GITHUB_ENV"
      - 
        name: Check tag name
        run: |
          echo "====================="
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ env.TAG_NAME }}
          echo "====================="
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.TAG_NAME }}
