name: CI - Build and push dev docker image to dockerhub

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set image and tag names in env
        env:
          IMAGE_NAME: ml-vg-service-frontend
        run: |
          RELEASE_VERSION=dev
          echo "DOCKER_TAG_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$RELEASE_VERSION" >> "$GITHUB_ENV"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_TAG_NAME }}
