name: Test using tags in actions

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo "Nyash myash 1"
          echo $RELEASE_VERSION
          echo "Nyash myash 2"
          echo ${{ env.RELEASE_VERSION }}
          echo "Nyash myash 3"
