name: Test using tags in actions

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  get-current-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo "====================="
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag[1:] }}
          echo "====================="
