name: Test using tags in actions

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  get-current-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag name in env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test 1
        run: |
          echo "====================="
          echo $RELEASE_VERSION
          echo ${RELEASE_VERSION:1}
          echo ${{ env.RELEASE_VERSION }}
          echo "====================="
      - name: Test 2
        run: |
          echo "====================="
          echo ${RELEASE_VERSION:1}
          echo ${{ env.RELEASE_VERSION }}
          echo "====================="
